// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDueUMOc4cDEBVA0m8tsMzh0q_oZg6H98g',
    appId: '1:92544135193:web:800e6a1b589faadd607a88',
    messagingSenderId: '92544135193',
    projectId: 'smash-gift-38b23',
    authDomain: 'smash-gift-38b23.firebaseapp.com',
    storageBucket: 'smash-gift-38b23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMsl0AI1y9O-KfaSw_DLo5MpBPlD0lZQ',
    appId: '1:92544135193:android:a834f34266398e9d607a88',
    messagingSenderId: '92544135193',
    projectId: 'smash-gift-38b23',
    storageBucket: 'smash-gift-38b23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6o51HFgQ6AMhZsG1gPg3kzDsn7ByVcs',
    appId: '1:92544135193:ios:6fe1c12a8750a84c607a88',
    messagingSenderId: '92544135193',
    projectId: 'smash-gift-38b23',
    storageBucket: 'smash-gift-38b23.appspot.com',
    iosClientId: '92544135193-e53a57t38m82lsrreiid97iomkri8jli.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX6o51HFgQ6AMhZsG1gPg3kzDsn7ByVcs',
    appId: '1:92544135193:ios:6fe1c12a8750a84c607a88',
    messagingSenderId: '92544135193',
    projectId: 'smash-gift-38b23',
    storageBucket: 'smash-gift-38b23.appspot.com',
    iosClientId: '92544135193-e53a57t38m82lsrreiid97iomkri8jli.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
